### PR TITLE
make logging config location configurable

### PR DESCRIPTION
**Pull request by jwestgard**
resolves https://issues.umd.edu/projects/LIBFCREPO/issues/LIBFCREPO-545

### CODE REVIEW

**Comment by peichman-umd** [comment]
@jwestgard The purpose of the current `config/logging.yml` file is to provide a default set of logging options. Could this PR be updated to make the `LOGGING_CONFIG` option optional, and fallback to that default if it is not present?

```python
logging_config_filename = repo_config.get('LOGGING_CONFIG', 'config/logging.yml')
with open(logging_config_filename, 'r') as logging_config_file:
    logging_options = yaml.safe_load(logging_config_file)
```

**Comment by peichman-umd** [comment]
@jwestgard I also see that we would need to make the fallback path absolute, and not just the string `config/logging.yml`, in order to run from any working directory.

**Comment by peichman-umd** [comment]
@jwestgard On further examination of this, I will go ahead and merge your PR, since that is a working configurable logging config implementation. I'll open a separate issue to provide the fallback default config via a module and not a YAML file.

**Comment by jwestgard** [comment]
Thanks. FWIW, I am totally fine with having that default. I think one option perhaps could be to use os.getcwd to find the working directory at runtime and calculate the location relative to that?

**Pull request merged**
